//Create an array of button four colours
var buttonColors=["red","blue","green","yellow"];

//Create an empty array to store the game  pattern generated by the nextSequence method.
var gamePattern=[];

//Create an empty array to store the user clicked pattern.
var userClickedPattern=[];

var started=false;

// To track the level of the game
var level=0;



//To detect when any Buttons are pressed and if pressed an ananomous function is called.
$(".btn").click(function(){
    //to get the element by id when the button is clciked.
    var userChosenColour=$(this).attr("id");
    //console.log(userChosenColor);

    //to push the user chosen colour inside the array of userChosenPattern.
    userClickedPattern.push(userChosenColour);
    //console.log(userClickedPattern);
    
    //play sounds according to the user clicking pattern
    playSound(userChosenColour);

    //to add animation to the chosen button when the user clicks on the button.
    animatePressed(userChosenColour);

    checkAnswer(userClickedPattern.length-1);

});

//to start the game when the first keypress is detected.
$(document).keypress(function(){
    if(started===false){
        $("#level-title").text("Level "+level);
        nextSequence();
        started=true;
    }
});

//function to check answer , if the users pattern and the game's pattern is same or not,
function checkAnswer(currentLevel){
    if(userClickedPattern[currentLevel]===gamePattern[currentLevel]){
        //console.log("success");
        if(userClickedPattern.length===gamePattern.length){
            setTimeout(function(){
                nextSequence();
            },1000)
        }
    }
    else{
        $("#level-title").text("Game Over, Press Any Key to Restart");
        playSound("wrong");
        $("body").addClass("game-over");
        setTimeout(function(){
            $("body").removeClass("game-over")
        },200);
        startOver();

        //console.log("wrong");
    }
}



//function created to restart the game
function startOver(){
    level=0;
    gamePattern=[];
    started=false;
}

function nextSequence(){
    userClickedPattern=[];
    level++;
    $("#level-title").text("level "+level);
    //To Create a random variable between 0 to 4
    var randomNumber= Math.floor(Math.random()*4);
    //console.log(randomNumber);
    
    //Created a variable called randomChosenColour to store the random color generated when the nextSequence method is called.
    var randomChosenColour=buttonColors[randomNumber];
    //console.log(randomChosenColour);

    //To push the randomChosen colour inside the game pattern array.
    gamePattern.push(randomChosenColour);

    //console.log(gamePattern);

    // Used jQuery to animate the randomChosenColour and make it flash 
    $("#"+ randomChosenColour).fadeOut(100).fadeIn(100).fadeOut(100).fadeIn(100);
    playSound(randomChosenColour);

}




//Created a function that takes an input parameter called name and used to play diffrent sound when calledwith the provided name.
function playSound(name){
    var audio=new Audio("sounds/"+name+ ".mp3");
    audio.play();
}

//Created a function to add a class pressed to the jQuery selected element and remove it after 100 milliseconds.
function animatePressed(currentColour){
    $("#"+currentColour).addClass("pressed");

    setTimeout(function(){
        $("#"+currentColour).removeClass("pressed");
    },100)
}